name: traver_v2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  introduction_screen: ^3.1.14
  pinput: ^5.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - .env
